FORWARD_FILE="/home/forward/$username"
FORWARD_PROCMAIL_FILE="/home/forward_procmail/$username"
FORWARD_MSG_FILE="/home/forward_msg/$username"
PROCMAIL_PATH="/usr/bin/procmail"
SENDMAIL_PATH="/usr/sbin/sendmail"
MAIL_DIR="$HOME/Maildir"
NEW_MAIL_FOLDER="new"
DOMAIN_NAME="cca.iac.es"
